const stocks = [
    { "ticker": "AAPL", "name": "Apple Inc." },
    { "ticker": "MSFT", "name": "Microsoft Corporation" },
    { "ticker": "GOOGL", "name": "Alphabet Inc." },
    { "ticker": "AMZN", "name": "Amazon.com Inc." },
    { "ticker": "META", "name": "Meta Platforms, Inc." },
    { "ticker": "NVDA", "name": "NVIDIA Corporation" },
    { "ticker": "TSLA", "name": "Tesla, Inc." },
    { "ticker": "AMD", "name": "Advanced Micro Devices, Inc." },
    { "ticker": "INTC", "name": "Intel Corporation" },
    { "ticker": "IBM", "name": "International Business Machines Corporation" },
    { "ticker": "CRM", "name": "Salesforce, Inc." },
    { "ticker": "ADBE", "name": "Adobe Inc." },
    { "ticker": "ORCL", "name": "Oracle Corporation" },
    { "ticker": "CSCO", "name": "Cisco Systems, Inc." },
    { "ticker": "QCOM", "name": "Qualcomm Incorporated" },
    { "ticker": "AVGO", "name": "Broadcom Inc." },
    { "ticker": "MU", "name": "Micron Technology, Inc." },
    { "ticker": "TXN", "name": "Texas Instruments Incorporated" },
    { "ticker": "SPOT", "name": "Spotify Technology S.A." },
    { "ticker": "PLTR", "name": "Palantir Technologies Inc." },
    { "ticker": "SNOW", "name": "Snowflake Inc." },
    { "ticker": "U", "name": "Unity Software Inc." },
    { "ticker": "AI", "name": "C3.ai, Inc." },
    { "ticker": "TWLO", "name": "Twilio Inc." },
    { "ticker": "NTNX", "name": "Nutanix, Inc." },
    { "ticker": "ZS", "name": "Zscaler, Inc." },
    { "ticker": "FTNT", "name": "Fortinet, Inc." },
    { "ticker": "NOW", "name": "ServiceNow, Inc." },
    { "ticker": "SPLK", "name": "Splunk Inc." },
    { "ticker": "CRWD", "name": "CrowdStrike Holdings, Inc." },
    { "ticker": "MDB", "name": "MongoDB, Inc." },
    { "ticker": "DDOG", "name": "Datadog, Inc." },
    { "ticker": "TEAM", "name": "Atlassian Corporation Plc" },
    { "ticker": "OKTA", "name": "Okta, Inc." },
    { "ticker": "DOCU", "name": "DocuSign, Inc." },
    { "ticker": "DBX", "name": "Dropbox, Inc." },
    { "ticker": "WDAY", "name": "Workday, Inc." },
    { "ticker": "SMAR", "name": "Smartsheet Inc." },
    { "ticker": "HUBS", "name": "HubSpot, Inc." },
    { "ticker": "SQ", "name": "Square, Inc." },
    { "ticker": "PINS", "name": "Pinterest, Inc." },
    { "ticker": "ROKU", "name": "Roku, Inc." },
    { "ticker": "ZM", "name": "Zoom Video Communications, Inc." },
    { "ticker": "SHOP", "name": "Shopify Inc." },
    { "ticker": "ETSY", "name": "Etsy, Inc." },
    { "ticker": "SNAP", "name": "Snap Inc." },
    { "ticker": "UBER", "name": "Uber Technologies, Inc." },
    { "ticker": "LYFT", "name": "Lyft, Inc." },
    { "ticker": "ABNB", "name": "Airbnb, Inc." },
    { "ticker": "DASH", "name": "DoorDash, Inc." },
    { "ticker": "CHWY", "name": "Chewy, Inc." },
    { "ticker": "PYPL", "name": "PayPal Holdings, Inc." },
    { "ticker": "V", "name": "Visa Inc." },
    { "ticker": "MA", "name": "Mastercard Incorporated" },
    { "ticker": "AXP", "name": "American Express Company" },
    { "ticker": "JPM", "name": "JPMorgan Chase & Co." },
    { "ticker": "GS", "name": "Goldman Sachs Group, Inc." },
    { "ticker": "MS", "name": "Morgan Stanley" },
    { "ticker": "BAC", "name": "Bank of America Corporation" },
    { "ticker": "C", "name": "Citigroup Inc." },
    { "ticker": "WFC", "name": "Wells Fargo & Company" },
    { "ticker": "SCHW", "name": "Charles Schwab Corporation" },
    { "ticker": "BLK", "name": "BlackRock, Inc." },
    { "ticker": "DIS", "name": "The Walt Disney Company" },
    { "ticker": "NFLX", "name": "Netflix, Inc." },
    { "ticker": "CMCSA", "name": "Comcast Corporation" },
    { "ticker": "WBD", "name": "Warner Bros. Discovery, Inc." },
    { "ticker": "VIAC", "name": "ViacomCBS Inc." },
    { "ticker": "EA", "name": "Electronic Arts Inc." },
    { "ticker": "ATVI", "name": "Activision Blizzard, Inc." },
    { "ticker": "TTWO", "name": "Take-Two Interactive Software, Inc." },
    { "ticker": "WMT", "name": "Walmart Inc." },
    { "ticker": "HD", "name": "The Home Depot, Inc." },
    { "ticker": "COST", "name": "Costco Wholesale Corporation" },
    { "ticker": "TGT", "name": "Target Corporation" },
    { "ticker": "LOW", "name": "Lowe's Companies, Inc." },
    { "ticker": "BBY", "name": "Best Buy Co., Inc." },
    { "ticker": "M", "name": "Macy's, Inc." },
    { "ticker": "JWN", "name": "Nordstrom, Inc." },
    { "ticker": "KSS", "name": "Kohl's Corporation" },
    { "ticker": "PFE", "name": "Pfizer Inc." },
    { "ticker": "JNJ", "name": "Johnson & Johnson" },
    { "ticker": "ABBV", "name": "AbbVie Inc." },
    { "ticker": "BMY", "name": "Bristol-Myers Squibb Company" },
    { "ticker": "GILD", "name": "Gilead Sciences, Inc." },
    { "ticker": "MRNA", "name": "Moderna, Inc." },
    { "ticker": "REGN", "name": "Regeneron Pharmaceuticals, Inc." },
    { "ticker": "AMGN", "name": "Amgen Inc." },
    { "ticker": "BIIB", "name": "Biogen Inc." },
    { "ticker": "LLY", "name": "Eli Lilly and Company" },
    { "ticker": "UNH", "name": "UnitedHealth Group Incorporated" },
    { "ticker": "CVS", "name": "CVS Health Corporation" },
    { "ticker": "PG", "name": "The Procter & Gamble Company" },
    { "ticker": "KO", "name": "The Coca-Cola Company" },
    { "ticker": "PEP", "name": "PepsiCo, Inc." },
    { "ticker": "MCD", "name": "McDonald's Corporation" },
    { "ticker": "SBUX", "name": "Starbucks Corporation" },
    { "ticker": "VZ", "name": "Verizon Communications Inc." },
    { "ticker": "T", "name": "AT&T Inc." },
    { "ticker": "NKE", "name": "Nike, Inc." },
    { "ticker": "BA", "name": "Boeing Company" },
    { "ticker": "CAT", "name": "Caterpillar Inc." },
    { "ticker": "DE", "name": "Deere & Company" },
    { "ticker": "XOM", "name": "Exxon Mobil Corporation" },
    { "ticker": "CVX", "name": "Chevron Corporation" },
    { "ticker": "BP", "name": "BP p.l.c." },
    { "ticker": "TOT", "name": "TotalEnergies SE" },
    { "ticker": "TTE", "name": "TotalEnergies SE" },
    { "ticker": "LMT", "name": "Lockheed Martin Corporation" },
    { "ticker": "GD", "name": "General Dynamics Corporation" },
    { "ticker": "NOC", "name": "Northrop Grumman Corporation" },
    { "ticker": "RTX", "name": "Raytheon Technologies Corporation" },
    { "ticker": "LHX", "name": "L3Harris Technologies, Inc." },
    { "ticker": "BAH", "name": "Booz Allen Hamilton Holding Corporation" },
    { "ticker": "TDG", "name": "TransDigm Group Incorporated" },
    { "ticker": "TT", "name": "Trane Technologies plc" },
    { "ticker": "DOV", "name": "Dover Corporation" },
    { "ticker": "RBC", "name": "RBC Bearings Incorporated" },
    { "ticker": "ITW", "name": "Illinois Tool Works Inc." },
    { "ticker": "XYL", "name": "Xylem Inc." },
    { "ticker": "CMI", "name": "Cummins Inc." },
    { "ticker": "PCAR", "name": "PACCAR Inc" },
    { "ticker": "TXT", "name": "Textron Inc." },
    { "ticker": "HON", "name": "Honeywell International Inc." },
    { "ticker": "GE", "name": "General Electric Company" },
    { "ticker": "MMM", "name": "3M Company" },
    { "ticker": "F", "name": "Ford Motor Company" },
    { "ticker": "GM", "name": "General Motors Company" },
    { "ticker": "FCAU", "name": "Fiat Chrysler Automobiles N.V." },
    { "ticker": "NSANY", "name": "Nissan Motor Co., Ltd." },
    { "ticker": "TM", "name": "Toyota Motor Corporation" },
    { "ticker": "HMC", "name": "Honda Motor Co., Ltd." },
    { "ticker": "VWAGY", "name": "Volkswagen AG" },
    { "ticker": "BMWYY", "name": "Bayerische Motoren Werke Aktiengesellschaft" },
    { "ticker": "DMLRY", "name": "Daimler AG" },
    { "ticker": "PSA", "name": "Peugeot S.A." },
    { "ticker": "RENA", "name": "Renault S.A." },
    { "ticker": "HYMTF", "name": "Hyundai Motor Company" },
    { "ticker": "KIMTF", "name": "Kia Motors Corporation" },
    { "ticker": "SZKMY", "name": "Suzuki Motor Corporation" },
    { "ticker": "MITSY", "name": "Mitsubishi Motors Corporation" },
    { "ticker": "NSANF", "name": "Nissan Motor Co., Ltd." },
    { "ticker": "VOLVY", "name": "Volvo Car Group" },
    { "ticker": "JAGX", "name": "Jaguar Land Rover Limited" },
    { "ticker": "GME", "name": "GameStop Corp." },
    { "ticker": "AMC", "name": "AMC Entertainment Holdings Inc." },
    { "ticker": "BB", "name": "BlackBerry Limited" },
    { "ticker": "BBBY", "name": "Bed Bath & Beyond Inc." },
    { "ticker": "EXPR", "name": "Express, Inc." },
    { "ticker": "KODK", "name": "Eastman Kodak Company" },
    { "ticker": "NOK", "name": "Nokia Corporation" },
    { "ticker": "SNDL", "name": "Sundial Growers Inc." },
    { "ticker": "SPCE", "name": "Virgin Galactic Holdings, Inc." },
    { "ticker": "MCD", "name": "McDonald's Corporation" },
    { "ticker": "SBUX", "name": "Starbucks Corporation" },
    { "ticker": "YUM", "name": "Yum! Brands, Inc." },
    { "ticker": "DRI", "name": "Darden Restaurants, Inc." },
    { "ticker": "CMG", "name": "Chipotle Mexican Grill, Inc." },
    { "ticker": "PNRA", "name": "Panera Bread Company" },
    { "ticker": "SHAK", "name": "Shake Shack Inc." },
    { "ticker": "WING", "name": "Wingstop Inc." },
    { "ticker": "PZZA", "name": "Papa John's International, Inc." },
    { "ticker": "DPZ", "name": "Domino's Pizza, Inc." },
    { "ticker": "GIS", "name": "General Mills, Inc." },
    { "ticker": "K", "name": "Kellogg Company" },
    { "ticker": "CAG", "name": "Conagra Brands, Inc." },
    { "ticker": "CPB", "name": "Campbell Soup Company" },
    { "ticker": "HRL", "name": "Hormel Foods Corporation" },
    { "ticker": "SJM", "name": "The J.M. Smucker Company" },
    { "ticker": "KHC", "name": "The Kraft Heinz Company" },
    { "ticker": "PEP", "name": "PepsiCo, Inc." },
    { "ticker": "KO", "name": "The Coca-Cola Company" },
    { "ticker": "MDLZ", "name": "Mondelez International, Inc." },
    { "ticker": "HSY", "name": "The Hershey Company" },
    { "ticker": "CL", "name": "Colgate-Palmolive Company" },
    { "ticker": "CHD", "name": "Church & Dwight Co., Inc." },
    { "ticker": "POST", "name": "Post Holdings, Inc." },
    { "ticker": "LW", "name": "Lamb Weston Holdings, Inc." },
    { "ticker": "FLO", "name": "Flowers Foods, Inc." },
    { "ticker": "BGS", "name": "B&G Foods, Inc." },
    { "ticker": "SENEA", "name": "Seneca Foods Corporation" },
    { "ticker": "LANC", "name": "Lancaster Colony Corporation" },
    { "ticker": "UNFI", "name": "United Natural Foods, Inc." },
    { "ticker": "SPTN", "name": "SpartanNash Company" },
    { "ticker": "CASY", "name": "Casey's General Stores, Inc." },
    { "ticker": "DG", "name": "Dollar General Corporation" },
    { "ticker": "DLTR", "name": "Dollar Tree, Inc." },
    { "ticker": "WMT", "name": "Walmart Inc." },
    { "ticker": "COST", "name": "Costco Wholesale Corporation" },
    { "ticker": "TGT", "name": "Target Corporation" },
    { "ticker": "KR", "name": "The Kroger Co." },
    { "ticker": "SVU", "name": "Supervalu Inc." },
    { "ticker": "IMKTA", "name": "Ingles Markets, Incorporated" },
    { "ticker": "WEIS", "name": "Weis Markets, Inc." },
    { "ticker": "VSI", "name": "Vitamin Shoppe, Inc." },
    { "ticker": "GNC", "name": "GNC Holdings, Inc." },
    { "ticker": "NTRI", "name": "Nutrisystem, Inc." },
    { "ticker": "MED", "name": "Medifast, Inc." },
    { "ticker": "THS", "name": "TreeHouse Foods, Inc." },
    { "ticker": "PFGC", "name": "Performance Food Group Company" },
    { "ticker": "FARM", "name": "Farmer Bros. Co." },
    { "ticker": "SMPL", "name": "The Simply Good Foods Company" },
    { "ticker": "BYND", "name": "Beyond Meat, Inc." },
    { "ticker": "TCS", "name": "Tata Consultancy Services Limited" },
   { "ticker": "INFY", "name": "Infosys Limited" }
  
  ];
  
  // const stocks = [...new Set(stocksK.map(stock => stock.ticker))];
  export default stocks;
  